name: Update Filter Header
on:
  push:
    branches:
      - main
    paths:
      - 'filter.txt'

jobs:
  update-header:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Version and Push
        env:
          TZ: 'Asia/Seoul'
        run: |
          KST_DATE=$(date +'%Y.%m.%d')
          FILE="filter.txt"

          if grep -q "! Version: $KST_DATE" "$FILE"; then
            echo "Version is up to date already."
            exit 0
          fi

          sed -i "0,/^! Version: .*/s/^! Version: .*/! Version: $KST_DATE/" "$FILE"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add "$FILE"
          git commit -m "chore: update filter version to $KST_DATE (KST)"
          git push
